server:
 port: 7903
spring:
  application:
    name: provoder-project
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
  cache:
    type: redis
  redis:
    timeout: 500000
eureka:
 client:
  service-url:
   defaultZone: http://user:password123@localhost:8761/eureka
mybatis:
  mapper-locations:
    - com/ibm/jiuzai/dao/*.xml