server:
 port: 7900
spring:
  application:
    name: provoder-login
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mysql
  cache:
    type: redis
  redis:
    timeout: 500000
eureka:
 client:
  service-url:
   defaultZone: http://user:password123@localhost:8761/eureka
mybatis:
  mapper-locations:
    - com/ibm/jiuzai/dao/*.xml